config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: "home#index"
  resources :users do
    resources :projects do
      resources :tasks do
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :title, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :name, :due_date , presence: true
  validates :name, length: {maximum: 100}

  attr_accessor :due_in

  def due_in
      (self.due_date - Date.current()).to_i
  end

  def set_priority
    if due_in < 3
      self.update(priority: 'Urgent')
    elsif due_in < 7
      self.update(priority: 'High')
    elsif due_in < 15
      self.update(priority: 'Med')
    else
      self.update(priority: 'Low')
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, with: :couldnt_find_record
  rescue_from NoMethodError, with: :no_method_error
  rescue_from ActionController::RoutingError, with: :no_route_error

  private
  def couldnt_find_record
    redirect_to root_url, alert: "That record doesn't exist."
  end

  def no_method_error
    redirect_to root_url, notice: "Sorry. An error has occurred and it is probably our fault."
  end

  def no_route_error
    redirect_to root_url, notice: "Sorry. An error has occurred and it is probably our fault."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  #index
  def index
    @projects = Project.all
  end

  #new
  def new
    @project = Project.new
  end

  #create
  def create
    project = current_user.projects.new(project_params)
    if project.save
      flash[:notice] = "New project created! Go ahead and add the first task."
      redirect_to user_project_path(current_user, project)
    else
      render :new
    end
  end

  #show
  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks.sort_by &:due_in
  end

  #edit
  def edit
    @project = Project.find(params[:id])
  end

  #update
  def update
    project = Project.find(params[:id])
    if project.update(project_params)
      flash[:notice] = "Your changes to #{project.title} bave been saved."
      redirect_to user_project_path(current_user, project)
    else
      render :edit
    end
  end

  #destroy
  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to user_projects_path(current_user)
  end

  private
  def project_params
    params.require(:project).permit(:title, :due_date, :image, :description, :status)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :image, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :image, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end

  def create
    project = Project.find(params[:project_id])
    task = project.tasks.new(task_params)
    if task.save
      flash[:notice] = "Woohoo! New task created."
      redirect_to user_project_path(current_user, project)
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
    @due_in = @task.due_in
    @task.set_priority
  end

  def edit
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
  end

  def update
    project = Project.find(params[:project_id])
    task = Task.find(params[:id])
    if task.update(task_params)
      flash[:notice] = "Good new! Everything went smoothly and your task is updated."
      redirect_to user_project_task_path(current_user, project, task)
    else
      render :edit
    end
  end

  def destroy
    task = Task.find(params[:id])
    project = task.project
    task.destroy
    redirect_to user_project_path(current_user,project)
  end

  private

  def task_params
    params.require(:task).permit(:name, :priority, :due_date, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2> About Get It Done </h2>
<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Small Steps</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="content">
      <h1><%= link_to 'Small Steps', root_path %></h1>
      <div class="user-info login">
             <% if current_user %>
               Welcome, <%= current_user.first_name %>
               <%= link_to 'Signout', destroy_user_session_path, :method => :delete, :class => "button"%>
             <% else %>
               <%= link_to 'Signup', new_user_registration_path, :class => "button"%>
               <%= link_to 'Login', new_user_session_path, :class => "button" %>
             <% end %>
      </div>
  </header>
  <% if notice %>
    <p class="notification-banner notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="notification-banner alert"><%= alert %></p>
  <% end %>
  <div class="content" id="main">
    <nav>
      <% if current_user %>
      <%= link_to 'View My Projects', user_projects_path(current_user) %>
      <% else %>
        <%= link_to 'Login to View Projects', user_session_path %>
      <% end %>
      <%= link_to 'Start New Project', new_user_project_path(current_user) %>
    </nav>


    <%= yield %>
  </div>

</body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div class="alert notification-banner"><%= @project.errors.full_messages.first%></div>
<% end %>
<div class="field">
  <%= form_for ([current_user, @project]) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.label :due_date %>
    <%= f.date_field :due_date %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.label :status %>
    <%= f.select(:status, ['Open', 'Closed']) %>
    <%= f.submit %>
  <% end %>
</div>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
<div class="item-view">
  <h2><%= link_to project.title, user_project_path(current_user, project) %></h2>
    <p><%= project.description %></p>
    <div class="image-container">
      <%= image_tag(project.image) %>
    </div>
    <%= link_to 'View',user_project_path(current_user, project), :class => "button" %>
  </div>
<% end %>

app/views/projects/new.html.erb
<div>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
  <div class="task-bucket item-view">
    <h2><%= @project.title %></h2>
    <% @tasks.each do |task| %>
      <% task.set_priority %>
      <div class="row">
        <%= link_to task.name, user_project_task_path(current_user, @project, task), class: 'task' %>
        <% if task.status == 'Closed' %>
          <aside class="due" id='done'>Done!</aside>
        <% else %>
          <!-- just a suggestion on next line, don't implement like this -->
          <aside class='<%= "due priority__#{task.priority}" %>'><%= task.due_in%> days left</aside>
          <!-- end suggestion -->
          <% if task.priority == 'High' || task.priority == 'Urgent' %>
            <aside class='due' id='soon'><%= task.due_in%> days left</aside>
          <% elsif task.priority == 'Med'%>
            <aside class='due' id='later'><%= task.due_in%> days left</aside>
          <% else %>
            <aside class='due'><%= task.due_in%> days left</aside>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <%= link_to '+', new_user_project_task_path(current_user, @project), class: 'button' %>
  </div>


  <div class="item-view">
    <h2>Details</h2>
    <ul>
      <li><div class="image-container"><%= image_tag(@project.image) %></div></li>
      <li><%= @project.description %></li>
      <li>Start Date: <%= @project.created_at.to_date %></li>
      <li>Due Date: <%= @project.due_date %></li>
      <li>Status: <%= @project.status %></li>
      <li>Created by: <%= @project.user.first_name %> <%= @project.user.last_name %></li>
    </ul>
    <%= link_to 'Edit Project', edit_user_project_path(current_user, @project), class: 'button' %>
    <%= link_to 'Delete', user_project_path(current_user, @project), method: :delete, class:'button' %>
  </div>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <div class="alert notification-banner"><%= @task.errors.full_messages.first%></div>
<% end %>
<h2><%= @project.title %> ></h2>
<div class="field">
  <%= form_for ([current_user, @project, @task]) do |f| %>
    <%= f.label 'Task'%>
    <%= f.text_field :name %>
    <%= f.label :due_date%>
    <%= f.date_field :due_date %>
    <%= f.label :status %>
    <%= f.select(:status, ['Open', 'Closed']) %>
    <%= f.submit%>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div>
  <%= render 'form' %>
</div>

app/views/tasks/new.html.erb
<div>
  <%= render 'form' %>
</div>

app/views/tasks/show.html.erb
  <div class="item-view">
    <h2><%= @task.name %></p></h2>
    <ul>
      <li>Parent Project: <%= link_to @task.project.title,user_project_path(current_user, @task.project)  %></li>
      <li>Due: <%= @task.due_date %></li>
      <li>Status: <%= @task.status %></li>
      <li>Priority: <%= @task.priority %></li>
      <li>Created by: <%= @task.project.user.first_name %> <%= @task.project.user.last_name%></li>
      <li>Due in: <%= @due_in %> days</li>
    </ul>
    <%= link_to 'Edit', edit_user_project_task_path(current_user, @task.project, @task), class: 'button' %>
    <%= link_to 'Delete', user_project_task_path(current_user, @task.project, @task), method: :delete, class:'button' %>
  </div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>